apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: fluxcdtutorial
spec:
  encryptedData:
    password: AgA2j3cb1O/7boV63rW9ijJCGzZJzSRbsz4HSfQ9EIXIua2i30IsrmQXVhcwwSFFKR+myDRxTZC3kIo5YyXCuKSRFc55dZHYRt1ip6TQepMPx5eRtnR5ooGlN7EjK63D+PYbEkdVTdFKGTwoexTv6H0BpBTMXvk/Q/kfROm7c0Lb+lFS3jfe6QgN70VUfXtaACPZoHUonkTM0hRhRM6eUwZ5cQbBvoLdfcUcwkL6dWg0N8n8b52LuQvmqS0bRHhK7nsmASI5gY2sTrYF71OErjIh/HhXZwVEQkDpBYhrlC0IuQLasNWROC6C+3lKxEv2ml8zTkwjN9/ORh4R3op7tvju3rEEuC1kHOvffskumD/C2JLBSEw62mzN2nQ/QtWpBDet21+iEIOSasLbW2mwbp1A6+ModFoOzGwYmeeRlrK8qvD3GvW99LtPZ//JDKOLKSbF0X8Wd7pJhFR2vPcYe5aE/1Ob3zwKxaScJomGZ4IhQ8AHbIi250RcTswLdBwgDFTP7u81FW3azpaC2KvT4VC+3lP5H1lkjYwFtSag/sM/fYbsJqtD2IWP4G9OsV9ToqADnG48FtHxIt6HkVfkGOM9j/O9PnYmSJBDTNyyyyrV5x2fowb5tAM1VAKzqK1l/MHKtzeSPTdTKc2JpuELnTC/IOBvlTSg87rNBCVbzPFqjSioG36qvRRNLFp7Cqfyh7+KcFr549CFFg==
    username: AgBAlE5SCpF9DWNHpUiULrxXPiJReSxxVQqOXpwEeCeLhClwPi9OohxIn7xY5bSGXCz4Th357+joTyRzDq3RGTPCaUFheBQxTifbypjH+rnXAWuPQbqjdjt5K0QTzwm1C/eUJcUzzkljzVEOzXkGWSCEbPh05GwRw5bDB9PZsgzv71q9s1kFkaD7dBzr5StwIwTgoUipKBOjxhCx8Uk9BuxAGL1DZUKRHpsTJ9qQMXOkshO9WKEHspqQvw+GiAkhdw/GLTF6StmC3e8uzSVO7QqaEnTPj+pBjtizjFxq8B+uUxi4Ac2aiM55fLcuOyEnoMVu5ci4myW8+VCs87FZgaw0W9gqopoRTdj9li1bM+4Zair5OrRLYWq3tQutqLlbZv11IJqIRUiSEW4aqbjlnJusWZZsXSCTU9jTC3SfqcOizsHNFEn0X7ZfWlHPDx9BTCJ6p1xK44cVwfrFlxOE12UOBjD+YxTgyHGtvtE8wxOwfqiWExYoFCTKiOaLlCGsy6YmjGWpnJli0TIOlETCKBhUT6ARv+KlgUc/vN+MBBd4phIk+W/Z+6tuB2DdgCzM4/TAket2CMJUAbdqZCNyEt4WoUTeq2Dsle2nHoMmhufwEWtnaEvpAdjvE2RYNkRTKLGapWpTykvj41Zry3XngTrFlBIzwnCj/Zl2KWQznTHjpAbsjJX5yeoibxQxHsbl5Imo6GUpnBs9QQ==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: fluxcdtutorial

